# Generated by Django 3.1.12 on 2024-12-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tutor', models.CharField(max_length=255)),
                ('period', models.IntegerField()),
                ('description', models.TextField()),
                ('total_students', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open for Registration'), ('running', 'Currently Running'), ('close', 'Closed')], default='close', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academyStart.category')),
            ],
        ),
    ]
