# Generated by Django 3.1.12 on 2024-12-17 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academyStart', '0002_auto_20241217_1058'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_registration',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'course')},
        ),
    ]
