# Generated by Django 3.1.12 on 2024-12-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyStart', '0003_auto_20241217_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
